version: "5.0.2"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rick-morty-api
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=server=mysql;port=3306;database=rickmortydb;user=root;password=root
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: rick-morty-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rickmortydb
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: